### ISSUE TITLE
DaysBetween: Seems to have weird date parsing now

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/zeroclickinfo-goodies#1261] opened 2015-07-09 09:08 UTC
![image](https://cloud.githubusercontent.com/assets/978048/8591756/54f1328a-2622-11e5-8d88-f391e83cd418.png)

![image](https://cloud.githubusercontent.com/assets/978048/8591772/6c18df08-2622-11e5-83e7-18150bf26d37.png)

**Comment by Bujiraso** [comment] 2015-07-11 21:11
I started to dig into this a bit and noticed that this is actually affecting another Goodie, WorkdaysBetween, in a similar way.
![ddg workdays](https://cloud.githubusercontent.com/assets/1975771/8635415/fb21ca58-27f7-11e5-9f92-1da31f28da8b.png)

What was surprising to me was that WeekdaysBetween is unaffected by the problem.
![ddg weekdays](https://cloud.githubusercontent.com/assets/1975771/8635418/0d0fda2a-27f8-11e5-94dc-4daec4ecccc4.png)

Still hacking at it a bit but I thought that was noteworthy.

**Comment by Bujiraso** [comment] 2015-07-11 21:29
The offending line appears to be:
`my ($date1, $date2) = parse_all_datestrings_to_date($1, $2);`
This line is present in both of the malfunctioning Goodies where WeekdaysBetween instead parses the dates individually like so:
`my ($start, $end) = (parse_datestring_to_date($1), parse_datestring_to_date($2));`

So it seems the Dates role may be overwriting the start date, so I'm gonna have a hack at that.
I've already added in a test into DaysBetween.t in order to catch relative date errors in future changes, but I'm a bit short on ideas for what to test in WorkdaysBetween, since it seems a more complicated case to drum up two relative dates with a fixed answer for -- if anyone has a suggestion that works, fire it my way and I'll add it in.

**Comment by Bujiraso** [comment] 2015-07-12 01:13
In the Dates role, it appears that the `parse_datestring_to_date` function isn't reacting properly when given a base. 
If I substitute out
````perl
my $date_object = ($dates_to_return[0]
                        ? parse_datestring_to_date($date, $dates_to_return[0])
                        : parse_datestring_to_date($date)
                    );
````

With the simpler line `my $date_object = parse_datestring_to_date($date);`, the problem is muted and the correct answer is returned for all of the above affected Instant Answers.
So it seems the case where a base is included as an argument for `parse_datestring_to_date` might be causing the issue.

**Comment by Bujiraso** [comment] 2015-07-12 02:29
I have made a pull request which should fix the noted regression, but there is some strange functionality that should probably be discussed here or in another issue. If you type "days between yesterday and today", the answer is (correctly) returned as 0. This is, however, entirely the unexpected answer. 
Where it may make sense to assume that the base date is the first date given on a days between query (e.g. days between May 22 and next week would calculate "next week" from May 22 and not the current day), this behaviour is not necessarily sensical when the second argument is "today". 

In any case where the first argument is a date, absolute or relative, if the second argument is "today", the answer would be 0, but that seems to be how it's currently designed to work.

**Comment by Bujiraso** [comment] 2015-07-12 13:46
After thinking @mintsoft 's comment on my PR, my revised question is this: are there any cases where a base date would be used with a relative term? Should "Jan 22 to next month" be expected to say a relative number from Jan 22, like 9 (days till Feb 1) or 30/31 (days till Feb 22)? I would imagine the expected behaviour is "days between Jan 22 and the next month from today", but I know not everyone necessarily thinks the same.

Going with the case that my expected behaviour is correct, by changing the line I just sent a PR for (` my $tmp_date = $base_time->clone();`) in `parse_all_datestrings_to_date` to simply get the current time instead of using a base, this seems to fix all issues that I can come up with, including ones with absolute dates with relative dates, bare months, etc.

In that case where my expected behaviour is the correct one, this PR should likely not be merged, because I can send another PR with the better changes that I currently have.

**Comment by mintsoft** [comment] 2015-07-12 14:19
@Bujiraso I think we'll keep the convo in the PR from now if that's OK?

**Comment by Bujiraso** [comment] 2015-07-12 16:28
Other than the one comment I left there before reading this: sounds good!

**Closed** 2016-03-01 16:43 UTC
Labels: Bug, Priority: High, Relevancy
