### ISSUE TITLE
Currency Cheat Sheet: Add currency symbols to content

### ISSUE THREAD

**Issue by nemeth** [duckduckgo/zeroclickinfo-goodies#1690] opened 2015-10-24 22:12 UTC
Because the Cheat Sheet Goodie allows ['symbols'](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/CheatSheets.pm#L23) as a trigger word the search term ['currency symbols'](https://duckduckgo.com/?q=currency+symbols) will display the currency cheat sheet, which - unfortunately- doesn't contain any symbol for the listed currencies. This behaviour might be confusing for the user.

-----
IA Page: https://duck.co/ia/view/currency_cheat_sheet

**Comment by amitdev** [comment] 2015-11-24 14:51
Submitted pull request #1806.

**Comment by moollaza** [comment] 2015-11-26 22:08
@amitdev thanks for making a PR. For future reference, if you put `Fixes #1806` in the description of your PR it will automatically ensure the issue is closed when the PR is merged, and make a note here that the issue was mentioned in your PR :+1:

**Closed** 2015-11-27 14:47 UTC
Labels: Bug, Priority: Medium, Relevancy
