### ISSUE TITLE
Use a Pull Request template to simplify workflow

### ISSUE THREAD

**Issue by laurenancona** [duckduckgo/zeroclickinfo-goodies#2750] opened 2016-03-14 22:27 UTC
Perhaps this saves @moollaza a few cycles spent reminding contribs to add the IA address to the pull.

[Documentation](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

Possible consequences include the need to revisit @daxtheduck's PR auto-responder/deploy verbiage, but maybe not. 

*PR forthcoming*

**Comment by GuiltyDolphin** [comment] 2016-03-14 22:29
@laurenancona This is on his tasks! He'll get around to it at *some point* I'm sure :wink:

**Comment by laurenancona** [comment] 2016-03-14 22:46
<img src="http://i.giphy.com/xHydpzVPGgLIs.gif">

**Comment by GuiltyDolphin** [comment] 2016-03-15 13:37
@laurenancona Bit obscure :wink:

**Comment by moollaza** [comment] 2016-04-01 04:44
Thanks @laurenancona for the suggestion! I do plan on making a PR and Issue template, just haven't gotten around to it.

If you'd like to start a PR I'd be happy to comment.

For issues I was going to have them describe what the issue is, how we can reproduce it, and also make sure they provide an example URL. It wouldn't hurt to get their browser/OS when necessary.

The footer should have a placeholder for the IA Page and the Maintainer as well (you can see these when you create a new issue for an Instant Answer via an existing IA Page: https://duck.co/ia/view/r_cheat_sheet

Pull Requests should explain what was done and why. It also should have them list out the issue(s) their PR solves. It must be in the format `Fixes #1234` so that GitHub will automatically close the linked issue when the PR is merged. 

For first timers we'd like to have them optionally tell us how they found out about DuckDuckHack -- we're considering a more formal "entrance" survey though so that may be replaced.

As well for PR's we need the IA Page link and Maintainer.

How does that sound?

**Comment by GuiltyDolphin** [comment] 2016-04-01 10:14
@moollaza The bit about 'if you're new to DuckDuckHack...' is great, but I found it started to get in the way a bit after a while on the old templates we were using - so the 'entrance' survey sounds like it'd be a nice alternative!

**Comment by GuiltyDolphin** [comment] 2016-05-01 07:00
@laurenancona We've got one now! Feel free to make suggestions/improvements! :cat:

**Closed** 2016-05-04 11:39 UTC
Labels: Suggestion
