### ISSUE TITLE
Parcelforce: Trigger MS KBs

### ISSUE THREAD

**Issue by zappe** [duckduckgo/zeroclickinfo-goodies#3986] opened 2017-03-07 20:36 UTC
When search for Microsoft KBs this trigger.

------
IA Page:  http://duck.co/ia/view/parcelforce 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft

**Comment by pjhampton** [comment] 2017-03-07 20:47
Thanks for reporting. I can't reproduce. Can you please give us the precise query, @zappe?

![screen shot 2017-03-07 at 8 46 16 pm](https://cloud.githubusercontent.com/assets/8960296/23677218/2422ae7a-0377-11e7-85a1-a26d806b5dd4.png)

**Comment by mintsoft** [comment] 2017-03-07 20:48
@pjhampton I think he means: https://duckduckgo.com/?q=KB2553549&t=ffab&ia=answer

**Comment by zappe** [comment] 2017-03-07 20:58
Sorry, yes that was what I meant.

**Comment by mintsoft** [comment] 2017-03-07 21:06
I'll workaround this in: https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3907

**Comment by mintsoft** [comment] 2017-03-07 21:11
@zappe @pjhampton Fixed in: #3907

**Closed** 2017-03-07 21:21 UTC
Labels: Status: Discussion
