### ISSUE TITLE
Local Sunrise/Sunset: Can we trigger just on sunset?

### ISSUE THREAD

**Issue by whmountains** [duckduckgo/zeroclickinfo-goodies#3762] opened 2016-11-17 21:54 UTC
I see in the source code that this is supposed to display today's sunset/sunrise for keywords like, "sunset", "what time is sunset", etc.  Right now I can only get it to work with a specific date, like "sunset 171116".

This works: https://duckduckgo.com/?q=sunset+171116
Can we make this work too?: https://duckduckgo.com/?q=sunset
------
IA Page:  http://duck.co/ia/view/sun_info 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @Mailkov

**Comment by mintsoft** [comment] 2016-11-17 22:58
@whmountains it's probably worth saying that https://duckduckgo.com/?q=sunset+today&ia=answer works :)

**Comment by mintsoft** [comment] 2016-11-17 22:59
Actually; this is a duplicate of: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3359

The answer is there in the answer tab but the wikipedia fathead has taken priority

**Closed** 2016-11-17 23:00 UTC
Labels: Maintainer Input Requested, Suggestion, Triggering

**Comment by whmountains** [comment] 2016-11-18 03:13
gotcha, thanks!
