### ISSUE TITLE
More at Vim Cheat sheet should be changed

### ISSUE THREAD

**Issue by grijeshsaini** [duckduckgo/zeroclickinfo-goodies#1239] opened 2015-07-05 09:20 UTC
Hi ,

In the vim cheat sheet the more at link is again redirected to duckduckgo.com.
"metadata": {
        "sourceName": "VimCheatSheet",
        "sourceUrl": "https://duckduckgo.com"
    },
I think it should be changed to http://vim.rtorr.com/

**Comment by moollaza** [comment] 2015-07-06 19:09
@grijeshsaini thanks! Closing this as a duplicate of #1234

**Closed by moollaza** 2015-07-06 19:09 UTC
Labels: Low-Hanging Fruit
