### ISSUE TITLE
Conversions: 

### ISSUE THREAD

**Issue by 37** [duckduckgo/zeroclickinfo-goodies#1867] opened 2015-12-08 23:56 UTC
@mintsoft 
"300mph to kmh", or even "300 miles per hour to kilometers per hour"

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by mintsoft** [comment] 2016-01-09 11:33
Duplicate of: https://github.com/duckduckgo/zeroclickinfo-goodies/issues/955

**Comment by mintsoft** [comment] 2016-01-09 11:34
@37 I've closed this issue as it's covered by another one, it's not resolved yet however when #955 is resolved it'll be tackled at the same time

**Closed by mintsoft** 2016-01-09 11:34 UTC
Labels: Improvement
