### ISSUE TITLE
Eclipse IDE Cheat Sheet: It's throwing a JS Error

### ISSUE THREAD

**Issue by bsstoner** [duckduckgo/zeroclickinfo-goodies#1646] opened 2015-10-08 21:07 UTC
![screen shot 2015-10-08 at 5 06 25 pm](https://cloud.githubusercontent.com/assets/126358/10379919/fd1b4bc2-6dde-11e5-8a1c-59c21f873e70.png)

------
IA Page:  http://duck.co/ia/view/eclipse_cheat_sheet

**Comment by moollaza** [comment] 2015-10-09 14:28
@bsstoner I'm unable to re-create this, but I don't think anything has changed. All the cheatsheets run the same JS so if there's a bug, we *should* see it for all Cheat Sheets.

Are you still able to produce this?

**Comment by preemeijer** [comment] 2015-10-10 20:27
I also tried it right now and I also can't reproduce the error...

**Comment by mintsoft** [comment] 2015-10-12 17:47
@bsstoner @moollaza I've just reproduced it here

**Comment by mintsoft** [comment] 2015-10-12 17:58
@bsstoner @moollaza now I've expanded it I think it's that this is commented out and the JSON contains `*/`:
![image](https://cloud.githubusercontent.com/assets/978048/10434724/36550b30-7113-11e5-9c84-ad3103c8ef87.png)

**Comment by moollaza** [comment] 2015-10-27 18:21
@mintsoft great find! I've confirmed this as well. It only happens in Chrome for me. Firefox seems to be OK.

<img width="2047" alt="developer_tools_-_https___duckduckgo_com__q_eclipse_cheat_sheet_ia_cheatsheet_iax_1_and_eclipse_cheat_sheet_at_duckduckgo" src="https://cloud.githubusercontent.com/assets/873785/10768111/e1520328-7cb5-11e5-8246-6011b990df65.png">

@bsstoner I'd say this is an internal (or browser) bug? Is there a reason we have that script tag commented out like that?

**Comment by mintsoft** [comment] 2015-10-27 19:47
@moollaza I think the problem is basically "javascript comment injection", it looks like to me like the script tag on the page is commenting out the content of the JSON (for some reason) and https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/cheat_sheets/json/eclipse.json#L388 isuncommenting it?

**Comment by moollaza** [comment] 2015-10-27 20:41
>That is to say, I don't think it's a browser bug, I think we're doing a weird thing!

@mintsoft what's odd though is that Firefox seems to ignore the `*/` in the JSON. I'm not sure if that's Firefox making a mistake, or being clever. I didn't check Safari yet though...

**Comment by moollaza** [comment] 2015-10-27 20:42
Yup, breaks in Safari as well.

**Comment by mintsoft** [comment] 2015-10-27 22:40
@moollaza hmm yeah, I guess it feels a little like it's a bug in Firefox to me! I don't see why it *wouldn't* break

**Comment by tagawa** [comment] 2016-06-03 12:51
Closing, as it looks like @Mailkov's PR fixed this.

**Closed by tagawa** 2016-06-03 12:51 UTC
Labels: Bug, CheatSheet, Internal
