### ISSUE TITLE
Calculator: "calculate" should be title cased

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#909] opened 2015-01-07 21:02 UTC
Looks like this at the moment:

![screen shot 2015-01-07 at 4 01 23 pm](https://cloud.githubusercontent.com/assets/81969/5653247/85363822-9686-11e4-84c6-d1e7aaabac85.png)

Can change it here: https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/Calculator.pm#L156

**Comment by mintsoft** [comment] 2015-01-07 21:57
Is this technically a duplicate? https://github.com/duckduckgo/zeroclickinfo-goodies/issues/904

**Comment by MrChrisW** [comment] 2015-01-07 22:45
Duplicate of #904

**Closed by MrChrisW** 2015-01-07 22:45 UTC
Labels: Low-Hanging Fruit
