### ISSUE TITLE
Timezone Converter: 

### ISSUE THREAD

**Issue by sajeshcherian** [duckduckgo/zeroclickinfo-goodies#4637] opened 2018-08-20 00:51 UTC
The IST to (PST, MST, CST, EST) is off by an hour. It probably doesn't check if DST is active or not.

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by moollaza** [comment] 2018-11-13 16:23
Duplicate of #4652

**Closed by moollaza** 2018-11-13 16:23 UTC

**Comment by sajeshcherian** [comment] 2018-11-13 16:31
If anything, #4652 was opened a month ago. My report was made 3 months ago. I would like to know what’s your policy on bug reports. I even mentioned what’s causing the issue.
