### ISSUE TITLE
Bang syntax on firefox Android with Ebay (!e)

### ISSUE THREAD

**Issue by abrahimladha** [duckduckgo/zeroclickinfo-goodies#4571] opened 2018-01-20 23:44 UTC
BUG FIX
    {IA Bang} Bug: Searching ebay with !e does not work on firefox android. If you query "!e shoes" or something, it instead will bring up ebay mobile as if you searched for the word "items"

    SUGGESTION
    It should return ebay mobile as if you searched 

    OTHER
    I have tried this on other versions of the firefox browser like beta and fennec and it is reproducable on those.
!e shoes on firefox mobile

---

Instant Answer Page: https://duck.co/ia/view/{ID}

**Comment by moollaza** [comment] 2018-02-14 21:01
@abrahimladha thanks for reporting, however I'm unable to reproduce this.

Regardless, this is the wrong place for this issue so I'm going to close it.

If we get an more reports we'll be sure to investigate further.

**Closed by moollaza** 2018-02-14 21:01 UTC

**Comment by abrahimladha** [comment] 2018-02-14 23:49
Here is a video: https://streamable.com/gwac3
Notice I search shoes, and test with the bang syntax for ebay, and it is as if I searched for "items".
If I go to duckduckgo.com first, then try the query "shoes !e" from the site rather than from my address bar I get the same issue. Also If I click on ebay ads by duckduckgo the same issue happens.

**Comment by moollaza** [comment] 2018-02-20 01:40
@abrahimladha do you have a region set on duckduckgo.com? What device are you using?

I'm still unable to recreate using FF on Android. Tested a couple devices via BrowserStack.com, using real devices.

**Comment by abrahimladha** [comment] 2018-02-20 06:02
Under many versions of firefox, I get the same issue (Firefox, Beta, Developer, and Fennec). Under any webview browser such as (AOSP browser, chrome) it seems to work fine. I have tried this on a nexus 6, and a nexus 9 and I am getting the same results across browsers. Is it possible the issue is with ebay? like you pass my query to ebay, "shoes", and the ebay site might be poor and it notices im not on webview and gets confused.

**Comment by moollaza** [comment] 2018-02-20 15:19
@abrahimladha do you have a region set on duckduckgo.com? Depending on the region toggle, we might be trying to send you to a different URL, but seeing as its going to Ebay.com it should be the same one I'm seeing.

I don't think it would be a bug on eBay's side as we generate the URL:

This should show you the URL we generate: 
https://api.duckduckgo.com/?q=!e+shoes&format=json&pretty=1&no_redirect=1&atb=v91-1_j

When I click that URL I get to the right search on eBay.

The generated eBay URL I see coming from our API is: 
`http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5574933636&toolid=10001&campid=5336728181&customid=&icep_uq=shoes&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg`

**Comment by abrahimladha** [comment] 2018-02-21 08:42
Right yeah I am going to settings and setting that to United States, and I tried a few other areas and the problem persists.
