### ISSUE TITLE
Conversions: floating point error (feet to inches)

### ISSUE THREAD

**Issue by mrkev** [duckduckgo/zeroclickinfo-goodies#1847] opened 2015-12-02 21:16 UTC
@mintsoft

Hello! I stumbled across this issue.
![screen shot 2015-12-02 at 4 13 40 pm](https://cloud.githubusercontent.com/assets/1285131/11544451/e618d334-990f-11e5-8c2e-d131dbc44e3d.png)

Thought I'd report it here.

------
IA Page:  http://duck.co/ia/view/conversions

**Comment by mintsoft** [comment] 2015-12-03 18:54
Thanks for the report @mrkev ! We'll look it into

**Comment by mrkev** [comment] 2015-12-03 18:54
:+1: 😊

**Comment by Mailkov** [comment] 2015-12-06 07:26
@mintsoft @mrkev 

I think the problem is that the factor is based on  the meter on Convert::Pluggable 
I found it on https://github.com/elohmrow/Convert-Pluggable/blob/master/lib/Convert/Pluggable.pm
```
{
            'unit'      => 'meter',
            'factor'    => '1',
            'aliases'   => ['meters', 'metre', 'metres', 'm'],
            'type'      => 'length',
        },
        {
            'unit'      => 'kilometer',
            'factor'    => '0.001',
            'aliases'   => ['kilometers', 'kilometre', 'kilometres', 'km', 'kms', 'klick', 'klicks'],
            'type'      => 'length',
        },
        {
            'unit'      => 'centimeter',
            'factor'    => '100',
            'aliases'   => ['centimeters', 'centimetre', 'centimetres', 'cm', 'cms'],
            'type'      => 'length',
        },
        {
            'unit'      => 'millimeter',
            'factor'    => '1000',
            'aliases'   => ['millimeters', 'millimetre', 'millimetres', 'mm', 'mms'],
            'type'      => 'length',
        },
        {
            'unit'      => 'mile',
            'factor'    => 1/1609.344,
            'aliases'   => ['miles', 'statute mile', 'statute miles', 'land mile', 'land miles', 'mi'],
            'type'      => 'length',
        },
        {
            'unit'      => 'yard',
            'factor'    => '1.0936133',
            'aliases'   => ['yards', 'yd', 'yds', 'yrds'],
            'type'      => 'length',
        },
        {
            'unit'      => 'foot',
            'factor'    => '3.28084',
            'aliases'   => ['feet', 'ft', 'international foot', 'international feet', 'survey foot', 'survey feet'],
            'type'      => 'length',
        },
        {
            'unit'      => 'inch',
            'factor'    => '39.3701',
            'aliases'   => ['inches', 'in', 'ins'],
            'type'      => 'length',
        },
```
probably the only solution is to round the result !!!

@mintsoft a question ... where is the code Convert :: Pluggable on DuckDuck?

**Comment by hemanth** [comment] 2015-12-06 10:17
@Mailkov The code is not on DDG, it's an [external](https://github.com/elohmrow/Convert-Pluggable) dependency.

**Comment by moollaza** [comment] 2015-12-12 03:35
@mrkev thanks for reporting this!

@Mailkov thanks for finding the bug!

Anyone care to submit a fix to C::P?

**Comment by Mailkov** [comment] 2015-12-12 12:20
@moollaza I submitted fix ...

**Comment by moollaza** [comment] 2015-12-14 20:26
@Mailkov thanks a lot! Once that's merged this will be fixed :+1:

**Closed** 2016-01-12 17:12 UTC
Labels: Bug, Priority: Medium, Relevancy
