### ISSUE TITLE
Bluej Commands Cheatsheet: 

### ISSUE THREAD

**Issue by aviatorpranoy** [duckduckgo/zeroclickinfo-goodies#3740] opened 2016-11-09 19:00 UTC
Any errors yet?
   

------
IA Page:  http://duck.co/ia/view/bluej_commands_cheatsheet 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @aviatorpranoy

**Comment by gautamkrishnar** [comment] 2016-11-11 16:43
Duplicate of #3743

**Closed by gautamkrishnar** 2016-11-11 16:43 UTC
