### ISSUE TITLE
Calculator:  I can't paste a formula

### ISSUE THREAD

**Issue by doggodanubus** [duckduckgo/zeroclickinfo-goodies#4676] opened 2018-12-20 15:31 UTC
I can't paste a formula in. -((( 20 * 1.5 ) / 100 ) - 20 )

I'm unable to paste anything into the box. 

------
IA Page:  http://duck.co/ia/view/calculator 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pjhampton

**Comment by moollaza** [comment] 2018-12-20 18:34
@doggodanubus thanks for the feedback. This is by design, I believe it is to prevent the user from entering a query the calculator can't parse. FWIW, Google's calculator behaves the same way.

Seeing as the search box is on the page though, you can paste it there and re-query. If the syntax is valid, the calculator will trigger again.

This will be marked as tolerated and closed.

**Closed by moollaza** 2018-12-20 18:34 UTC
Labels: Status: Tolerated
