### ISSUE TITLE
Timezone Converter: 

### ISSUE THREAD

**Issue by vasundhar** [duckduckgo/zeroclickinfo-goodies#4624] opened 2018-07-19 11:41 UTC
6:00 PM IST in CST results : -1 hour 

------
IA Page:  http://duck.co/ia/view/timezone_converter 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @GlitchMr

**Comment by moollaza** [comment] 2018-11-13 16:33
Duplicate of #4652

**Closed by moollaza** 2018-11-13 16:33 UTC
