### ISSUE TITLE
The figlet plugin seems to shadow the normal search.

### ISSUE THREAD

**Issue by homeworkprod** [duckduckgo/zeroclickinfo-goodies#923] opened 2015-01-15 23:03 UTC
A search for "figlet foo" shows both a figlet-generated ASCII banner for the string "foo" as well as normal search results.

A search for just "figlet", however, shows no results at all. Thus, it is not possible find out where the website of the figlet project is when searching for its name. There is no indication that something special is happening, leaving the user confused and unsatisfied.

I expect normal search results even when searching just for "figlet".

**Comment by mintsoft** [comment] 2015-01-15 23:45
Hi @homeworkprod thanks for the report. The IA you're seeing initially is the figlet IA which only triggers if there is a query following the word figlet (https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/lib/DDG/Goodie/FIGlet.pm#L44).

When I search for "figlet" (https://duckduckgo.com/?q=figlet&t=debian&ia=about) I see the main wikipedia driven IA at the top and the main website as the first link: 
![figlet](https://cloud.githubusercontent.com/assets/978048/5769218/7861fde4-9d10-11e4-8d60-3af68d2dd7e1.png)
Is that inconsistent with the results you're getting? If not can you upload a screenshot of what you're seeing?

Thanks

**Comment by homeworkprod** [comment] 2015-01-16 00:14
This is the result I see in Chromium 39.0 on Linux:

![ddg_figlet_no-results](https://cloud.githubusercontent.com/assets/95277/5769497/b5d7d75a-9d1c-11e4-9995-00998ee78de6.png)

It looks like that on Iceweasel 31.3.0/Linux as well.

**Comment by mintsoft** [comment] 2015-01-16 00:20
@homeworkprod Interesting; I can't reproduce this at all. Could you add a screenshot of the network inspector (Ctrl+Shift+i and then refresh/F5) and see if there are any errors; 404 or 500 etc?

**Comment by homeworkprod** [comment] 2015-01-16 01:41
@mintsoft: Actually, I cannot. Turns out that _now_ the behaviour seems to have changed.

As you can see in the screenshot I posted above, it was taken when viewing the URL https://duckduckgo.com/?q=figlet
Now, however, that URL redirects to https://duckduckgo.com/?q=figlet&ia=about – a page that indeed shows what your screenshot contains.

I can confirm that it works now in both Chromium and Firefox. No browser extensions like NoScript or similar seemed to be interfering, but now and earlier.

Maybe I hit a server with faulty config or plugin version or something.

**Comment by mintsoft** [comment] 2015-01-16 12:45
@homeworkprod Hmm interesting. 

@jagtalon @moollaza Not sure about this at all; any ideas?

**Comment by moollaza** [comment] 2015-01-19 03:21
@mintsoft @homeworkprod that's certainly odd. It seems like everything is working correctly now, and the URL modification you're experiencing is expected. Once an IA displays, the link changes so you can share that. Likewise if you click another IA the URL will update so that the link indicates which IA should be shown on page load.

I'll close this for now but will keep an eye out for any similar issues.

Thanks again for reporting this @homeworkprod!

**Closed by moollaza** 2015-01-19 03:21 UTC
Labels: Relevancy

**Comment by mintsoft** [comment] 2015-01-19 12:39
@moollaza is there any other information which would be useful to gather in this situtation should anything similar reappear?

**Comment by moollaza** [comment] 2015-01-19 21:06
@mintsoft hmm I'm not really sure. Knowing the users's general location always helps so, if need be, we can investigate the regional machine that they were likely being served by to see if the problem exists only on that machine. It may have been a very temporary wiki outage on that machine that got cached, but our ops guys haven't mention any outages so I think it's safe to assume all systems are operational.

**Comment by homeworkprod** [comment] 2015-01-20 03:17
Let me know if there are any details you might need and which I should be able to provide.
