### ISSUE TITLE
Cheat Sheet Controller: Shows Ace editor for the query "cheat sheet" 

### ISSUE THREAD

**Issue by Jab2870** [duckduckgo/zeroclickinfo-goodies#3517] opened 2016-08-09 16:26 UTC
When you search for cheat sheet in duck duck go, this shows.

------
IA Page:  http://duck.co/ia/view/cheat_sheets

**Comment by edgesince84** [comment] 2016-08-09 19:30
thanks @Jab2870 - I don't see why this would trigger, but I'll relay it to the staff.  thanks!

**Comment by tagawa** [comment] 2016-08-10 01:33
I don't think it's the cheat sheet that's the problem, I think our IA platform is handling the query "cheat sheet" wrong - it looks for a cheat sheet with a blank name, can't find one so picks the first one it finds (Ace Editor).

I've submitted this as an issue in the platform repository so closing here. Thanks for noticing and reporting @Jab2870!

**Comment by moollaza** [comment] 2016-08-10 17:38
@tagawa this is actually all controlled by the Cheat Sheet Goodie so this repo is appropriate 👍

**Comment by moollaza** [comment] 2016-08-10 17:44
@tagawa @Jab2870 looks like the issue is actually with the Ace Editor JSON. It specifies `""` as an alias, which is technically valid...

**Comment by moollaza** [comment] 2016-08-10 17:47
Made a PR: #3520

**Comment by tagawa** [comment] 2016-08-12 08:58
@moollaza Ah, my mistake. Thanks.

**Closed** 2016-08-16 16:56 UTC
Labels: Bug, PR Received, Priority: High, Relevancy
