### ISSUE TITLE
Gimp Cheatsheet: Bottom text is getting cut-off

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-goodies#947] opened 2015-01-21 19:53 UTC
![screen shot 2015-01-21 at 2 51 43 pm](https://cloud.githubusercontent.com/assets/81969/5843814/31ded312-a17d-11e4-9b6c-906b0268189a.png)
https://duck.co/ia/view/gimp_cheat_sheet

**Comment by MrChrisW** [comment] 2015-01-22 00:56
This is by design [see CSS](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/gimp_cheat_sheet/gimp_cheat_sheet.html#L4-L5)

Easy solution is to adjust the `max-height` value, however text can still be cut off if the window is resized:

![gimp](https://cloud.githubusercontent.com/assets/5282264/5848533/656cf690-a214-11e4-96d9-d9d862ba43c3.png)

**Comment by tagawa** [comment] 2015-03-15 14:23
Looks like this could be closed &mdash; the live CSS contains "max-height: 45ex;" which fixes it for me.

**Comment by altern8tif** [comment] 2015-07-05 10:12
@jagtalon Time to close this :+1:  Fixed in #1180.

**Comment by MrChrisW** [comment] 2015-07-05 10:32
@altern8tif :+1:

**Closed by MrChrisW** 2015-07-05 10:32 UTC
Labels: Bug, CheatSheet, Design, Low-Hanging Fruit
